
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP INDIA
 */
public class Records extends javax.swing.JInternalFrame {

    /**
     * Creates new form SearchOrder
     */
    public Records() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jScrollPane2.setViewportView(jTextPane1);

        setClosable(true);
        setIconifiable(true);
        setTitle("RECORDS");

        jLabel1.setText("Bill No.");

        jLabel2.setText("Name");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bill No.", "Order Id", "Name", "Contact", "Address", "Products", "Rate", "Quantity", "Amount", "Total", "Discount", "Final bill", "Date"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("View All");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try
        {
            Connection myconnection;
            String path="jdbc:mysql://localhost/";
            String place="deliverysystem";
            String username="root";
            String password="";
            myconnection=DriverManager.getConnection(path+place,username,password);
            try
            {
                
                String q="select * from orderdetails where BillNo=?";
                PreparedStatement mystatement=myconnection.prepareStatement(q);
                  mystatement.setString(1, jFormattedTextField1.getText());
                  ResultSet myresult=mystatement.executeQuery();
                  DefaultTableModel mymodel=(DefaultTableModel)jTable1.getModel();
                  if(myresult.next())
                  {
                     
                      mymodel.setRowCount(0);
                      do
                      {String Billno,Id,Name,Contact,Address,Products,Rate,Amount,Quantity,Total,Discount,Final_bill,Date;
                       Billno=myresult.getString("BillNo");
                       Id=myresult.getString("Orderno");
                       Name=myresult.getString("Name");
                       Contact=myresult.getString("Contact");
                       Products=myresult.getString("Products");
                       Address=myresult.getString("Address");
                      Quantity=myresult.getString("Quantity");
                      Rate=myresult.getString("Rate");
                      Total=myresult.getString("Total");
                       Amount=myresult.getString("ptotal");
                      Discount=myresult.getString("Discount");
                      Final_bill=myresult.getString("Final bill");
                       Date=myresult.getString("Date");
                   
                       mymodel.addRow(new Object[]{Billno,Id,Name,Contact,Address,Products,Rate,Quantity,Amount,Total,Discount,Final_bill,Date});
                   }
                   while(myresult.next());
                     
            }   
                  else
                  {
                         JOptionPane.showMessageDialog(rootPane, "No data found");
                  }
                
               
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane, "Error"+e.getMessage());
            }
            finally
            {
                myconnection.close();
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, "Error"+e.getMessage());
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
           try
        {
            Connection myconnection;
            String path="jdbc:mysql://localhost/";
            String place="deliverysystem";
            String username="root";
            String password="";
            myconnection=DriverManager.getConnection(path+place,username,password);
         try{
            
                String q="select * from orderdetails where  name like ?";
                PreparedStatement mystatement=myconnection.prepareStatement(q);
                  mystatement.setString(1, jTextField1.getText()+'%');
                  ResultSet myresult=mystatement.executeQuery();
                  DefaultTableModel mymodel=(DefaultTableModel)jTable1.getModel();
                  if(myresult.next())
                  {
                      mymodel.setRowCount(0);
                       
                      do
                      {String Billno,Id,Name,Contact,Address,Products,Rate,Amount,Quantity,Total,Discount,Final_bill,Date;
                       Billno=myresult.getString("BillNo");
                       Id=myresult.getString("Orderno");
                       Name=myresult.getString("Name");
                       Contact=myresult.getString("Contact");
                       Products=myresult.getString("Products");
                       Address=myresult.getString("Address");
                      Quantity=myresult.getString("Quantity");
                      Rate=myresult.getString("Rate");
                      Total=myresult.getString("Total");
                       Amount=myresult.getString("ptotal");
                      Discount=myresult.getString("Discount");
                      Final_bill=myresult.getString("Final bill");
                       Date=myresult.getString("Date");
                   
                       mymodel.addRow(new Object[]{Billno,Id,Name,Contact,Address,Products,Rate,Quantity,Amount,Total,Discount,Final_bill,Date});
                      }
                   while(myresult.next());
                     
            }   
                      
                  else
                  {
                         JOptionPane.showMessageDialog(rootPane, "No data found");
                  }
                
               
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane, "Error"+e.getMessage());
            }
            finally
            {
                myconnection.close();
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, "Error"+e.getMessage());
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
    
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
   try
        {
            Connection myconnection;
            String path="jdbc:mysql://localhost/";
            String place="deliverysystem";
            String username="root";
            String password="";
            myconnection=DriverManager.getConnection(path+place,username,password);
         try{
            
                String q="select * from orderdetails ";
                PreparedStatement mystatement=myconnection.prepareStatement(q);
                 
                  ResultSet myresult=mystatement.executeQuery();
                  DefaultTableModel mymodel=(DefaultTableModel)jTable1.getModel();
                  if(myresult.next())
                  {
                      mymodel.setRowCount(0);
                       
                      do
                      {String Billno,Id,Name,Contact,Address,Products,Rate,Amount,Quantity,Total,Discount,Final_bill,Date;
                       Billno=myresult.getString("BillNo");
                       Id=myresult.getString("Orderno");
                       Name=myresult.getString("Name");
                       Contact=myresult.getString("Contact");
                       Products=myresult.getString("Products");
                       Address=myresult.getString("Address");
                      Quantity=myresult.getString("Quantity");
                      Rate=myresult.getString("Rate");
                      Total=myresult.getString("Total");
                       Amount=myresult.getString("ptotal");
                      Discount=myresult.getString("Discount");
                      Final_bill=myresult.getString("Final bill");
                       Date=myresult.getString("Date");
                   
                       mymodel.addRow(new Object[]{Billno,Id,Name,Contact,Address,Products,Rate,Quantity,Amount,Total,Discount,Final_bill,Date});
                      }
                   while(myresult.next());
                     
            }   
                      
                  else
                  {
                         JOptionPane.showMessageDialog(rootPane, "No data found");
                  }
                
               
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane, "Error"+e.getMessage());
            }
            finally
            {
                myconnection.close();
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, "Error"+e.getMessage());
            
        }    
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
